Repository javascript-tutorial/zh-hant.javascript.info, pull requests merged in 2019-08, with the labels that each got.

#4 Update README.md to be zh-Hant-TW
  README.md
Labels: needs +1, review needed

#5 An Introduction to JavaScript
  1-js/01-getting-started/1-intro/article.md
Labels: needs +1, proofreading needed

#8 Revert "readme"
  README.md
Labels: help wanted

#6 Code editors
  1-js/01-getting-started/3-code-editors/article.md
Labels: needs +1, proofreading needed, review needed

#10 The modern mode, "use strict"
  1-js/02-first-steps/03-strict-mode/article.md
Labels: needs +1, proofreading needed, review needed

#7 Developer console
  1-js/01-getting-started/1-intro/article.md
  1-js/01-getting-started/4-devtools/article.md
  1-js/01-getting-started/index.md
Labels: needs +1, proofreading needed, review needed

#9 Code structure
  1-js/02-first-steps/02-structure/article.md
Labels: needs +1, proofreading needed, review needed

#16 Type Conversions
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/solution.md
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/task.md
  1-js/02-first-steps/06-type-conversions/article.md
Labels: needs +1, proofreading needed, review needed

#14 Data types
  1-js/02-first-steps/05-types/1-string-quotes/solution.md
  1-js/02-first-steps/05-types/1-string-quotes/task.md
  1-js/02-first-steps/05-types/article.md
Labels: needs +1, proofreading needed, review needed

#13 Variables
  1-js/02-first-steps/04-variables/1-hello-variables/solution.md
  1-js/02-first-steps/04-variables/1-hello-variables/task.md
  1-js/02-first-steps/04-variables/2-declare-variables/solution.md
  1-js/02-first-steps/04-variables/2-declare-variables/task.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/task.md
  1-js/02-first-steps/04-variables/article.md
Labels: needs +1, proofreading needed, review needed

#20 [Proposal] PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs +1

#18 Fix formatting
  1-js/01-getting-started/1-intro/article.md
  1-js/01-getting-started/3-code-editors/article.md
  1-js/01-getting-started/4-devtools/article.md
  1-js/02-first-steps/02-structure/article.md
  1-js/02-first-steps/03-strict-mode/article.md
  1-js/02-first-steps/04-variables/1-hello-variables/task.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/task.md
  1-js/02-first-steps/04-variables/article.md
  1-js/02-first-steps/05-types/article.md
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/solution.md
  1-js/02-first-steps/06-type-conversions/article.md
  README.md
Labels: needs +1, review needed

#22 style: Modify file highlight for tasks
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs +1, review needed

#25 Interaction: alert, prompt, confirm
  1-js/02-first-steps/09-alert-prompt-confirm/1-simple-page/solution.md
  1-js/02-first-steps/09-alert-prompt-confirm/1-simple-page/task.md
  1-js/02-first-steps/09-alert-prompt-confirm/article.md
Labels: needs +1, proofreading needed, review needed

#21 Operators
  1-js/02-first-steps/07-operators/1-increment-order/solution.md
  1-js/02-first-steps/07-operators/1-increment-order/task.md
  1-js/02-first-steps/07-operators/2-assignment-result/solution.md
  1-js/02-first-steps/07-operators/2-assignment-result/task.md
  1-js/02-first-steps/07-operators/article.md
Labels: needs +1, proofreading needed, review needed
